### ISSUE TITLE
Support wheels for CUDA 12.1 and 12.2

### ISSUE THREAD

**Issue by choronz** [jllllll/exllama#9]
Can you kindly add CUDA 12.1 and 12.2 for Windows and Linux x64 ?

I notice that these are present for other related projects like llama_cpp_python and bitsandbytes. Thanks.

**Comment by jllllll** [comment]
llama_cpp_python and bitsandbytes have a wider range of supported CUDA versions due to them not being wholly reliant on Pytorch for functionality, and therefore not being tied to the CUDA version that Pytorch uses. Recent bitsandbytes updates have changed this somewhat, but it is still possible to use other CUDA versions easily with it as the kernels are not built through Pytorch.

I'll try to add CUDA 12.1 builds. However, keep in mind that this will require the use of nightly Pytorch builds which may result in inconsistent support should an incompatible Pytorch build get uploaded.

**Comment by jllllll** [comment]
CUDA 12.1 builds have been uploaded: https://github.com/jllllll/exllama/releases/latest
Please let me know if there are any issues.
